python main.py \
--model model.model \
--trainer trainer \
--dataset KUA \
--no 1 \
--dropout 0.2 --num_heads 8 --num_experts 6 --ffn_acti gelu --num_blocks 2 --hidden_dims 32 \
--early_fusion_type gate --transformer_num_heads 1 --transformer_num_blocks 3 --transformer_dropout 0.2 \
--trade_off 0.6 --max_epochs 500 \
--lr 0.001 --batch_size 1024 --seed 2023 \
--rec_weight 1.0 \
--contrast_type InstanceCL --cf_weight 0.1  --temperature 0.01 \
--seq_representation_type mean --seq_representation_instancecl_type concat \
--augment_type CoOccurrence --time_prob 0.2 --click_prob 0.3 --mask_ratio 0.1
