python main.py \
--model model.model \
--trainer trainer \
--dataset QKA \
--config_files ./config/ \
--no 1 \
--dropout 0.2 --num_heads 4 --num_experts 4 --ffn_acti gelu --num_blocks 2 --hidden_dims 32 \
--early_fusion_type sum --transformer_num_heads 8 --transformer_num_blocks 2 --transformer_dropout 0.2 \
--trade_off 0.7 --max_epochs 1000 \
--lr 0.001 --batch_size 1024 --seed 2023 \
--rec_weight 1.0  \
--contrast_type InstanceCL --cf_weight 0.1 --temperature 0.01 \
--seq_representation_type mean --seq_representation_instancecl_type concat \
--augment_type CoOccurrence --time_prob 0.8 --click_prob 0.6 --mask_ratio 0.9 
