python main.py \
--model model.model \
--trainer trainer \
--dataset QKV \
--no 1 \
--dropout 0.3 --num_heads 8 --num_experts 4 --ffn_acti gelu --num_blocks 3 --hidden_dims 32 \
--early_fusion_type sum --transformer_num_heads 2 --transformer_num_blocks 2 --transformer_dropout 0.2 \
--trade_off 0.6 --max_epochs 1000 \
--lr 0.001 --batch_size 1024 --seed 2023 \
--rec_weight 1.0 \
--contrast_type InstanceCL --cf_weight 0.001 --temperature 0.01 \
--seq_representation_type mean --seq_representation_instancecl_type concat \
--augment_type CoOccurrence --time_prob 0.4 --click_prob 0.1 --mask_ratio 0.1
